[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.6",
    "mysql-connector-python>=9.1.0",
    "pydantic>=2.10.5",
    "python-dotenv>=1.0.1",
    "uvicorn>=0.34.0",
]
